import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-fixed": "#e2e2e5",
        "secondary-container": "#fed488",
        "tertiary-container": "#111c2d",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#c5c6ca",
        surface: "#f8f9fa",
        "error-container": "#ffdad6",
        "surface-container": "#edeeef",
        "inverse-primary": "#c6c6c9",
        "tertiary-fixed": "#d8e3fa",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "primary-fixed-dim": "#c6c6c9",
        "on-tertiary-container": "#798499",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#44474a",
        secondary: "#775a19",
        "on-secondary-fixed-variant": "#5d4201",
        "on-secondary-container": "#785a1a",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-variant": "#e1e3e4",
        "on-primary-container": "#838486",
        "inverse-on-surface": "#f0f1f2",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        "on-primary-fixed": "#1a1c1e",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5d5e61",
        "on-tertiary-fixed-variant": "#3c475a",
        primary: "#000101",
        "inverse-surface": "#2e3132",
        tertiary: "#000001",
        "primary-container": "#1a1c1e",
        outline: "#75777a",
        "on-tertiary-fixed": "#111c2c",
        "on-primary-fixed-variant": "#454749",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed": "#ffdea5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "48px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "stack-sm": "12px",
        "stack-md": "24px",
        gutter: "24px",
        "container-max": "1440px",
        "margin-tablet": "32px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        caption: ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "title-lg": [
          "20px",
          { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
